# Generated by Django 5.1.7 on 2025-03-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الخبر')),
                ('shortNews', models.TextField(verbose_name='لمحه عن  الخبر')),
                ('body', models.TextField(verbose_name='محتوى الخبر')),
                ('category', models.CharField(choices=[('سياسية', 'سياسية'), ('اقتصادية', 'اقتصادية'), ('ثقافية', 'ثقافية'), ('رياضية', 'رياضية'), ('تقنية', 'تقنية')], max_length=50, verbose_name='تصنيف الخبر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
            ],
        ),
    ]
