# Generated by Django 5.1.7 on 2025-03-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_news',
            name='image_news',
            field=models.ImageField(null=True, upload_to='pics/', verbose_name='صورة الخبر'),
        ),
    ]
